version: '3.9'

services:
  db:
    image: mysql
    environment:
      MYSQL_USER: addai
      MYSQL_PASSWORD: addai
      MYSQL_ROOT_PASSWORD: addai
      MYSQL_DATABASE: addai
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3308:3308"
    healthcheck:
      test: "/usr/bin/mysql --user=addai --password=addai --execute \"SHOW DATABASES;\""
      interval: 1s
      timeout: 20s
      retries: 10

  crm:
    image: electro_calc
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/addai"
      SPRING_DATASOURCE_USERNAME: addai
      SPRING_DATASOURCE_PASSWORD: addai
    ports:
      - "8083:8080"
    depends_on:
      db:
        condition: service_healthy
volumes:
  my-db: