spring:
  datasource:
#    url: jdbc:mysql://localhost:3308/electric_cal
#    username: user_elec
#    password: bios
    hikari:
      schema: electric_cal
  jpa:
    properties:
      hibernate.format_sql: true

logging:
  level:
    web: DEBUG
    org.hibernate.SQL: DEBUG
    #    org.hibernate.type.descriptor.sql: TRACE
    #    org.hibernate.type: DEBUG
    org:
      springframework:
        cache: TRACE
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
          client:
            RestTemplate: DEBUG

vaadin:
  productionMode: false
  compatibilityMode: false